# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: root
      POSTGRES_DB: app
      